/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_SerialPort */

#ifndef _Included_android_serialport_SerialPort
#define _Included_android_serialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_serialport_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_android_serialport_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     android_serialport_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_serialport_SerialPort_close
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_android_serialport_SerialPort_setScanTriggerGPIO
  (JNIEnv *, jclass, jint);
JNIEXPORT jint JNICALL Java_android_serialport_SerialPort_setScanWakeupGPIO
  (JNIEnv *, jclass, jint);
JNIEXPORT jint JNICALL Java_android_serialport_SerialPort_setScanPowerGPIO
  (JNIEnv *, jclass, jint); 
JNIEXPORT jint JNICALL Java_android_serialport_SerialPort_getReadGoodGPIO
  (JNIEnv *, jclass, jint);
#ifdef __cplusplus
}
#endif
#endif
